# $NetBSD: Makefile,v 1.13 2025/04/14 14:17:41 adam Exp $

DISTNAME=	djangocms_alias-3.0.2
PKGNAME=	${PYPKGPREFIX}-${DISTNAME:S/_/-/}
CATEGORIES=	www python editors
MASTER_SITES=	${MASTER_SITE_PYPI:=d/djangocms-alias/}

MAINTAINER=	abu.maryam@msafa.org
HOMEPAGE=	https://github.com/django-cms/djangocms-alias
COMMENT=	DjangoCMS plugin to replicate and extend the alias function
LICENSE=	modified-bsd

USE_LANGUAGES=	# none

.include "../../lang/python/wheel.mk"
.include "../../mk/bsd.pkg.mk"
