# $NetBSD: Makefile,v 1.13 2025/04/14 14:17:41 adam Exp $

DISTNAME=	django-parler-2.3
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	www python editors
MASTER_SITES=	${MASTER_SITE_PYPI:=d/django-parler/}

MAINTAINER=	abu.maryam@msafa.org
HOMEPAGE=	https://github.com/django-parler/django-parler
COMMENT=	Simple Django model translations without nasty hacks
LICENSE=	modified-bsd

USE_LANGUAGES=	# none

.include "../../lang/python/wheel.mk"
.include "../../mk/bsd.pkg.mk"
