# $NetBSD: Makefile,v 1.13 2025/04/14 14:17:41 adam Exp $

DISTNAME=	django_entangled-0.7
PKGNAME=	${PYPKGPREFIX}-${DISTNAME:S/_/-/}
CATEGORIES=	www python editors
MASTER_SITES=	${MASTER_SITE_PYPI:=d/django-entangled/}

MAINTAINER=	abu.maryam@msafa.org
HOMEPAGE=	https://github.com/jrief/django-entangled
COMMENT=	Edit JSON-Model Fields using a Standard Django Form
LICENSE=	modified-bsd

USE_LANGUAGES=	# none

.include "../../lang/python/wheel.mk"
.include "../../mk/bsd.pkg.mk"
