# $NetBSD: Makefile,v 1.13 2025/04/14 14:17:41 adam Exp $

DISTNAME=	djangocms_simple_admin_style-1.1.5
PKGNAME=	${PYPKGPREFIX}-${DISTNAME:S/_/-/}
CATEGORIES=	www python editors
MASTER_SITES=	${MASTER_SITE_PYPI:=d/djangocms-simple-admin-style/}

MAINTAINER=	abu.maryam@msafa.org
HOMEPAGE=	https://github.com/fsbraun/djangocms-simple-admin-style
COMMENT=	Lightweight alternative to the comprehensive Django CMS Admin Style
LICENSE=	modified-bsd

USE_LANGUAGES=	# none

.include "../../lang/python/wheel.mk"
.include "../../mk/bsd.pkg.mk"
