# $NetBSD: Makefile,v 1.13 2025/04/14 14:17:41 adam Exp $

DISTNAME=	djangocms_text-0.9.3
PKGNAME=	${PYPKGPREFIX}-${DISTNAME:S/_/-/}
CATEGORIES=	www python editors
MASTER_SITES=	${MASTER_SITE_PYPI:=d/djangocms-text/}

MAINTAINER=	abu.maryam@msafa.org
HOMEPAGE=	https://github.com/djangocms/djangocms-text
COMMENT=	Flexible and extensible rich text editing plugin for Django CMS
LICENSE=	modified-bsd

USE_LANGUAGES=	# none

.include "../../lang/python/wheel.mk"
.include "../../mk/bsd.pkg.mk"
