# $NetBSD: Makefile,v 1.13 2025/04/14 14:17:41 adam Exp $

DISTNAME=	django_fsm_2-4.1.0
PKGNAME=	${PYPKGPREFIX}-${DISTNAME:S/_/-/g}
CATEGORIES=	www python editors
MASTER_SITES=	${MASTER_SITE_PYPI:=d/django-fsm-2/}

MAINTAINER=	abu.maryam@msafa.org
HOMEPAGE=	https://github.com/django-commons/django-fsm-2
COMMENT=	Simple Django model translations without nasty hacks
LICENSE=	modified-bsd

USE_LANGUAGES=	# none

.include "../../lang/python/wheel.mk"
.include "../../mk/bsd.pkg.mk"
