# $NetBSD$

DISTNAME=       fitdecode-0.11.0
PKGNAME=        ${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=     devel
MASTER_SITES=   ${MASTER_SITE_PYPI:=f/fitdecode/}

MAINTAINER=	abu.maryam@msafa.org
HOMEPAGE=	https://github.com/polyvertex/fitdecode
COMMENT=	Python library to parse FIT files.
LICENSE=	mit

.include "../../lang/python/wheel.mk"
.include "../../mk/bsd.pkg.mk"
