# $NetBSD: Makefile,v 1.13 2025/04/14 14:17:41 adam Exp $

DISTNAME=	djangocms_frontend-2.2.0
PKGNAME=	${PYPKGPREFIX}-${DISTNAME:S/_/-/}
CATEGORIES=	www python
MASTER_SITES=	${MASTER_SITE_PYPI:=d/djangocms-frontend/}

MAINTAINER=	abu.maryam@msafa.org
HOMEPAGE=	https://github.com/django-cms/djangocms-frontend
COMMENT=	Versioning plugin for DjangoCMS
LICENSE=	modified-bsd

USE_LANGUAGES=	# none

.include "../../lang/python/wheel.mk"
.include "../../mk/bsd.pkg.mk"
